# Generated by Django 4.0.3 on 2022-04-07 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        ('environments', '0002_alter_environments_concentration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrosion_rate', models.IntegerField()),
                ('localized', models.CharField(max_length=255)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environments.environments')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.materials')),
            ],
        ),
    ]
