# Generated by Django 4.0.3 on 2022-04-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdata',
            name='corrosion_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
