# Generated by Django 4.0.3 on 2022-04-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environments',
            name='concentration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='environments',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='environments',
            name='temperature',
            field=models.IntegerField(),
        ),
    ]
